### ISSUE TITLE
Links in Python lectures need to be checked

### ISSUE THREAD

**Issue by jstac** [QuantEcon/meta#1]
@thomassargent30 reports a number of broken links, including in Exchangeability and Bayesian Updating.

> "A 'friend' recently told me after looking at our cite that when the links don't work it makes us look like amateurs. "

This is not good to hear.  These need to be fixed ASAP but we also should review how link checking takes place in order to avoid repeats.  I'm happy to help if I can.

BTW, @jlperla, do you have link checking system in place?  Perhaps we could share technology?

**Comment by jlperla** [comment]
@jstac I just have what Matt sent. Which I have been trying to schedule time to update on the Julia side with a merge soon. Sorry, been pretty chaotic the last few months, as you can imagine

**Comment by jstac** [comment]
Sure, I understand.  But I guess more people are relying on our lectures now.  Please let us know if we can help get that merged.

Also, @mmcky is developing a github actions framework for execution testing, link checking and previews that might also be of interest.  See, e.g., https://github.com/QuantEcon/lecture-python-intro/pull/134.

**Comment by jlperla** [comment]
@mmcky looks like the PR was merged in https://github.com/QuantEcon/lecture-source-jl/pull/807 but I forgot to get a new build initiated. Do you have a chance to initiate one?

**Comment by mmcky** [comment]
@jstac adding discussion here from my email

---

We discovered a bug this week where we had stale html files left on the python-advanced server. 
Essentially, when we moved `odu` from advanced to the intro lecture set a copy of the html stayed behind. 
I tidied up those files a couple days ago -- so the link would have started to present as broken at that time. 

Our automatic **weekly** link checker runs on Sunday so these types of errors only get caught on a weekly cycle. 
I can update the frequency to daily. 

I have taken a look at the `exchangeable` lecture.
When the links were initially added to `odu` it was in the python-advanced set of lectures.

`this lecture <https://python-advanced.quantecon.org/odu.html>`__ 

In general for links to python-advanced (from python-intro) documents this is the correct format as they are external links. 

However when `odu` moved to `lecture-intro` we can use `:doc:` links as odu is now colocated with exchangeable in the same repo

:doc:`this lecture <odu>`

For changes see: https://github.com/QuantEcon/lecture-python-intro/pull/136/files 

I have also reviewed navy_captain.rst and updated the `:doc:` links used to remove the `.html` extensions that were added. 

For changes see: https://github.com/QuantEcon/lecture-python-intro/pull/135/files

**Comment by mmcky** [comment]
@jlperla I have initiated a `clean` build to get all `pages` rebuilt.

**Comment by jstac** [comment]
Thanks @mmcky .  If I remember correctly, links are also getting checked in PRs now.  If we combine that with a weekly full check of the site, that full test of the site, that should be enough.  Agree?

**Comment by jlperla** [comment]
Thanks so much @mmcky

**Comment by mmcky** [comment]
@jlperla the latest build of the `julia` site is now live.

**Comment by mmcky** [comment]
All links in `python-programming`, `python-intro`, and `python-advanced` have been checked by the weekly link checker. The two links that remained have been fixed.
