### ISSUE TITLE
Track Changes in `@jit` in Numba Version`0.59.0.`

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/meta#112]
From [#294](https://github.com/QuantEcon/lecture-python-programming.myst/issues/294)

@jstac:
> Switch over to a simple @jit once 0.59 comes out

Keep track of changes in the [deprecation of fall-back behaviour](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit).

**Comment by mmcky** [comment]
I haven't seen the notices but our lectures are still using njit in
many cases, and probably jit(nopython=True) in a few cases.

See e.g., https://python-programming.quantecon.org/numba.html

**Comment by jstac** [comment]
These substitutions should be straightforward but touch many lectures -- and hence need to be coordinated with @mmcky

**Comment by mmcky** [comment]
@HumphreyYang we have now updated all backends to use `numba>=0.59` so I will add this to my list. Are there any examples that you know of that need updating?

**Comment by HumphreyYang** [comment]
Many thanks @mmcky. The examples in my mind are cases involving `@jit(nopython=True)`. I think we can simply change it to `@jit`. Here is an example where it is used: https://python.quantecon.org/mccall_model.html#implementation

**Comment by mmcky** [comment]
thanks @HumphreyYang I have opened a PR to review starting with `lecture-python.myst`
