### ISSUE TITLE
Prepare versions of notebooks without JIT for Tom

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#118]
> I am attaching to lectures that (a) seem to me to be good candidates, and (b) could actually be useful to me in a class I'll start teaching in a couple of weeks. 
They are the two "Cass-Koopmans lectures". Both just do some simple "shooting".

@HumphreyYang can I get your help on Monday to make a version of these notebooks that doesn't use `jit` for @thomassargent30

**Comment by HumphreyYang** [comment]
> @HumphreyYang can I get your help on Monday to make a version of these notebooks that doesn't use `jit` for @thomassargent30

Many thanks @mmcky,

Very happy to help! 

So is the aim here to port the two Cass-Koopmans lectures into non-jit versions in Jupyter notebooks format that can run on WASM? It would be great if I could have access to a WASM playground to have them tested.

Many thanks in advance.

**Comment by mmcky** [comment]
thanks @HumphreyYang -- please feel free to commit to

https://github.com/quantecon/project.lecture-wasm

This will load a jupyterlite environment as a gh-pages build. 

You can also run locally

https://jupyterlite.readthedocs.io/en/latest/quickstart/standalone.html#standalone-servers

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Could you please add me to the wasm repo so that I can publish my branch and PR?

Many thanks in advance.

**Comment by mmcky** [comment]
thanks @HumphreyYang I think this issue can now be closed.
