### ISSUE TITLE
Possible renaming of three Python lecture series

### ISSUE THREAD

**Issue by jstac** [QuantEcon/meta#2]
The names are now

1. Python Programming for Quantitative Economics
1. Introductory Quantitative Economics with Python
3. Advanced Quantitative Economics with Python

@thomassargent30 suggests we replace "Introductory" with "Basic".  

That's option A:

1. Python Programming for Quantitative Economics
1. Basic Quantitative Economics with Python
3. Advanced Quantitative Economics with Python

Option B is to simply drop the word, so the three series are then

1. Python Programming for Quantitative Economics
2. Quantitative Economics with Python
3. Advanced Quantitative Economics with Python

Option C is

1. Python Programming for Economics and Finance
2. Quantitative Economics with Python
3. Advanced Quantitative Economics with Python

If we go with option C, we could put some material on option pricing into series 1, which would be fun.  For example, Monte Carlo methods using GPUs!

**Comment by thomassargent30** [comment]
Dear John, I like options B and C. You choose please. I see your argument
for adding finance. Ok with me. Thanks, Tom

**Comment by jstac** [comment]
Hi @mmcky @shlff @Harveyt47 @drdrij @najuzilu, yet another of many recent changes, but -- unless any of you have strong objections -- we're going to go with option C.

@Harveyt47, would you mind to take the lead on this?  It's just a matter of figuring out all the places where the names appear.  Please do a careful search over all html / md / rst files in each of the three repos.  @mmcky and @drdrij can assist.  I'll review the PRs too.  Many thanks.

**Comment by mmcky** [comment]
@jstac can the `url` prefixes stay the same:

`python-programing`
`python-intro`
`python-advanced`

the issue with `python-intro` to `python` is that the `python.quantecon.org` currently hosts the landing page to unify the three linked to `lecture-python-website`. If you want to simplify that prefix in line with the title Andrij and I will need to review the infrastructure site for deployments.

**Comment by jstac** [comment]
Ah, yes, that's an issue.  I would prefer to change it but I I feel like we've done a lot of chopping and changing.  Let's leave it as is for now and then review some time down the road.

**Comment by DrDrij** [comment]
Good point @mmcky. Restoring the python.quantecon.org could fix some of the traffic and SEO - but we wouldn't have anywhere to house our landing page for the 3 lectures (unless it went on the org site homepage).

**Comment by jstac** [comment]
Well, if restoring python.quantecon.org would be helpful, then we could shift python-intro there and then the landing page for the 3 lectures could sit at quantecon.org/python-lectures?

**Comment by mmcky** [comment]
@DrDrij do you think this will help a lot given the current `google search` results I am getting now? Does google keep history like that? For me it makes sense to host the landing page at python.quantecon.org as it unifies the `python` pages together but I am happy to be overruled. `python-intro` won't make as much sense when we change the titles. I am a bit worried that people will go to python.quantecon.org and not find `programming` and `advanced` from the top symbol based navbar.

**Comment by jstac** [comment]
This is a tough one.

I'm feeling more and more @DrDrij 's point that the existing set up is too nested --- too many clicks to get down to one lecture.  So what we could do is have `python.quantecon.org` point to the middle one, which is the page now at `https://python-intro.quantecon.org/`.  From there, readers can either go ahead or switch to programming or advanced using the navigation bar with the Greek letters.

Now, as for @mmcky 's point, which is a very good one, we have to abandon these Greek letters and put in something more descriptive :-)

So how about "Programming", "Basic" and "Advanced" on that nav bar.

The three titles are still as per option C.

Finally, the existing landing page, currently at `python.quantecon.org`, gets moved to `quantecon.org/python-lectures`.

Are well all OK with this plan?  The URL `python-intro.quantecon.org` will no longer be needed, but perhaps we can route everything heading to that URL or below into `python.quantecon.org`.

I'm sorry I didn't plan this better guys...

Oh yeah, and one separate thing, which I know I shouldn't put here: I wrote somewhere -- no idea where now -- that I'd like those big GH buttons down the bottom of each of the three lecture landing pages ("The source files for these lectues are blah blah") to be terminated. Instead, we'll just have "View source" to the left of "View commits" on each of the three pages.  "View source" points at the corresponding GH repo.

**Comment by mmcky** [comment]
Roger that. Just a couple of questions:

1. The current `landing page` will just be linked from `quantecon.org` as an entry point right? 
1. should the repo be renamed from `lecture-python-intro` to `lecture-python` to maintain conventions?

Here is a checklist of things that need to be updated and changed. 

**Infrastructure:**

- [ ] update QuantEcon.aws.admin for build scripts for publishing (@mmcky)
- [ ] setup PR on `org site` to migrate `python` landing page and redirect front page `python` lecture link to new landing page location. (@DrDrij)
- [ ] update `python` landing page with new link location for `python-intro` (@DrDrij)
- [ ] update top `quantecon` navbar with new landing page location for `python` lectures (@DrDrij). This needs to be done for `python-programming`, `python`, and `python-advanced`
- [ ] update `lecture-python-intro` repository name to `lecture-python`
- [ ] update `lecture-python-intro.theme` repository name to `lecture-python.theme`

**Lecture Repo:**

- [ ] update `lecture-python` with any internal changes needed to remove `Introductory`
- [ ] update `lecture-python-programming` with internal changes need for title change with `Finance` (i.e. conf.py, index.rst etc)

**Deployment:**

- [ ] update `sitemap.xml` files and inform google

**Comment by Harveyt47** [comment]
Hey @mmcky should I hold off on Lecture Repo tasks until after Infrastructure tasks are complete. Not certain is order matters here. 

There are four files in the lecture repo's which require the name changes.

1.	conf.py which I believe is used for the naming of the pdf and its url
2.	index.rst which the name is used for the title on the index page.
3.	Home.html which is the python.quantecon.org page we are changing.
4.	About.md which is a file documenting the history of the project. 

These are the only files that come up for me upon a name search for 
1.	Python Programming for Quantitative Economics
2.	Introductory Quantitative Economics with Python
in their respective repos.

**Comment by mmcky** [comment]
Thanks @Harveyt47. Please feel free to go ahead with setting up PR's that I can review. There shouldn't be many collisions with other changes so if the PR's stay open for a couple days that will be fine.

**Comment by jstac** [comment]
Really sorry @mmcky to be creating all that work :grimacing: .  I hate to use your hugely valuable time on these changes but I think the name change is necessary and I'm glad we'll end up with a less nested set of pages.

> The current landing page will just be linked from quantecon.org as an entry point right?

I'm not sure what the question is.  Would you mind to rephrase?

> should the repo be renamed from lecture-python-intro to lecture-python to maintain conventions?

I hate to say it but yes, I think we should bite the bullet and do it.  Thanks @mmcky

**Comment by mmcky** [comment]
No problem @jstac - just getting some structure in place for the migration. 

> Would you mind to rephrase?

Sure. We have a current landing page hosted at https://python.quantecon.org which will be migrated to be a page on the org site https://quantecon.org/python-lectures. I guess my question is will that page **only** be linked from:
1. The quantecon.org front page from the "Quantitative Economics with Python" button
1. the `Lectures` -> `Quantitative Economics with Python` button in the top QuantEcon navbar. 

Are you still happy with those as entry points?

Other uses will no doubt go directly to python.quantecon.org and then navigate sideways to either Programming or Advanced.

**Comment by jstac** [comment]
Yes, I'm happy with that.  My hope is that users will visit the uppper level landing page currently at `python.quantecon.org` only once.  In that way we avoid the deep nesting.

**Comment by mmcky** [comment]
@DrDrij when you are free can we link up to review `Infrastructure` tasks for this migration. Thanks.

**Comment by mmcky** [comment]
@DrDrij we are going ahead with the name change (before we do the swap in infrastructure)

Do you mind manually updating the names (as per Option C) for the landing page

https://python.quantecon.org

**Comment by DrDrij** [comment]
My tasks on your checklist are all completed @mmcky. Updated today:
- Added new sloan logo
- Migrated py landing page to org
- Migrated py landing about page to org
- QE Menubar now injected via single js file (no markup or css needed)
- Created PRs to flip org site links
- Updated qe menubar + sitebar in py theme repos
- Moved homepage github links to "View source" link

**Comment by mmcky** [comment]
thanks @DrDrij. As discussed last night we have merged the "visual" changes -- looks like the last piece of work will be to migrate the `bucket`. I plan to do this work on `wednesday` this week. I think it just will involved:

- [ ] review all current updates
- [ ] merge PR's for link adjustments 
- [ ] clean builds of all sites
- [ ] merge in updates to QuantEcon.aws.admin tools for new server locations
- [ ] add redirects to `python-intro` files back to `python bucket`

For the short term we won't be able to deploy with `deletion propogations` for `python.quantecon.org` bucket but I will enable `deletion propogation` for `programming` and `advanced` so we don't run into duplicate content if lectures are moved around. We will need to keep this in mind for `python` though in the short term while google adjusts back to `python` url

**Comment by mmcky** [comment]
Copying open items from comment above to refresh

**Infrastructure:**

- [ ] redirect front page `python` lecture link to new landing page location (@DrDrij). This will be done implicitly when we sync `lecture-python` for the first time which will replace the `index.html` file. 
- [ ] update `python` landing page with new link location for `python-intro` (@DrDrij)
- [ ] update top `quantecon` navbar with new location for `python intro` lectures (@DrDrij).
- [ ] update `lecture-python-intro` repository name to `lecture-python` (@mmcky)
- [ ] update `lecture-python-intro.theme` repository name to `lecture-python.theme` (@mmcky)
- [ ] archive `lecture-python-website` and migrate relevant issues to `meta` or `org` site is currently supporting the landing page once moved to the org site (@mmcky)

**Deployment:**

- [ ] update `sitemap.xml` files and inform google (@DrDrij)
- [ ] add redirects from `python-intro` bucket to `python`

**Comment by mmcky** [comment]
@jstac a bit of final tidy up left but all systems go for the new location for `python-intro` series. 

It is now hosted at python.quantecon.org and redirects are in place from `python-intro`.

@DrDrij can you update the sitemaps with Google?

**Comment by jstac** [comment]
Can we close this now @mmcky @DrDrij ?

**Comment by mmcky** [comment]
@jstac I have opened clean up issues in the other repositories. So we can go ahead and close this now. Thanks.
