### ISSUE TITLE
A reference link problem in lectures' downloadable ipynb files

### ISSUE THREAD

**Issue by shlff** [QuantEcon/meta#33]
Good evening, @jstac and @mmcky . @AakashGfude and I found a possible issue about downloadable ``ipynb`` files for all lectures: 

- Assume that we only download one lecture's ``ipynb`` file without downloading [reference](https://python.quantecon.org/zreferences.html)'s ``ipynb`` file. If, in the lecture's ``ipynb`` file, there is a link connecting to a paper in the reference, then the link cannot work.

We figured out there could be at least 2 feasible methods to solve this issue:
1. We can inform the audience to download the reference's ``ipynb`` file if they download the ``ipynb`` file for a lecture with reference links.
2. We can add a reference part to ``ipynb`` file of all lecture with reference links, like what we did in the ``pdf`` file of those lectures.

Do you think it is an issue? If so, which solution do you prefer?

**Comment by mmcky** [comment]
I just checked a recent download notebook and references are pointing to the website for `opt_transport`.

@shlff can you confirm if anything needs to be done here. I think this can be closed.

**Comment by shlff** [comment]
Thanks for your elegant proposal and beautiful work on fixing this issue @mmcky . 

I've randomly selected and checked the following lectures:
- ``muth_kalman``
- ``orth_proj``
- ``opt_transport``
- ``complex_and_trig``
- ``linear_algebra``

I can confirm that this issue should have been resolved and this issue could be closed.

**Comment by mmcky** [comment]
thanks @shlff
