### ISSUE TITLE
[awstats] Update

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#34]
It would be great to update (or aggregate) aws stats for the new lecture structure

This doesn't seem to be working
http://awstats.quantecon.org/awstats/awstats.pl?config=python.quantecon.org

**Comment by jstac** [comment]
Works fine for me.

**Comment by mmcky** [comment]
@jstac it looks like it is configured for python.quantecon.org -- just not sure if @DrDrij has updated so all sites use the same aws stats certificate so the results are aggregated over the three sites -- or if we have separate awsstats trackers. 

@DrDrij can you update when you have time. Thanks.

**Comment by mmcky** [comment]
Closing this as we have migrated to use Google Analytics for the lecture sites.
