### ISSUE TITLE
Italic for emphasis -> a colorscheme?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/meta#35]
Italics don't look great in a sans font: https://python.quantecon.org/samuelson.html#Samuelson%E2%80%99s-Model

How about we map `*this is emphasized*` to a different color font instead?

What do you think @DrDrij ?

**Comment by DrDrij** [comment]
I haven't included an italic version of the font by default for loading time reasons, but its a very popular font now. I think the rendering might be improved slightly. Shall I give that a go first @jstac ?
Also, let me style emphasised text with CSS, its pretty quick.

**Comment by jstac** [comment]
Whatever you think will look good.  Thanks @DrDrij ...

**Comment by DrDrij** [comment]
Loading the italic font did change some of the letters and readability.
I've setup 3 PRs. Lets see if the improvement is sufficient.
https://github.com/QuantEcon/lecture-python.theme/pull/15
https://github.com/QuantEcon/lecture-python-programming.theme/pull/17
https://github.com/QuantEcon/lecture-python-advanced.theme/pull/12

**Comment by mmcky** [comment]
thanks @DrDrij I will merge those theme PRs now.

**Comment by mmcky** [comment]
the above appears to have been merged. So closing this issue.
