### ISSUE TITLE
Some unicode issues (suggested by Numba)

### ISSUE THREAD

**Issue by jstac** [QuantEcon/meta#38]
From [this discussion](https://github.com/numba/numba/issues/4816) it seems we are better off using `\varphi` and `\varepsilon` in our code.

It would be good if someone could do a careful search and replace.

**Comment by mmcky** [comment]
@jstac this is a pretty old issue now. Do you think we need to loop through this and check. The lectures seem to be running well from an execution standpoint.

**Comment by jstac** [comment]
True that.  Closing.
