### ISSUE TITLE
Setup Template Repo for QuantEcon JupyterBook Theme

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#42]
Drawing inspriration from [sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme) we should prepare a repository for the quantecon jupyter-book theme that is in development with @DrDrij

**Comment by AakashGfude** [comment]
The created repository is at: https://github.com/QuantEcon/quantecon-book-theme

**Comment by mmcky** [comment]
thanks @AakashGfude
