### ISSUE TITLE
Update old Sloan Logos

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#45]
We need to update to newer Sloan logos on:

- [ ] https://python.quantecon.org
- [ ] https://python-programming.quantecon.org
- [ ] https://python-advanced.quantecon.org

@DrDrij. Given the shape change we may need some input on this.

**Comment by DrDrij** [comment]
Fortunately they have a square version of the logo. I think the following should do for now?

@mmcky Can you point me to the best place to edit the source files and I'll add the PRs? Are we using the myst repo yet?

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5886045/93706905-0fe71c00-fb6e-11ea-9fde-89f9b5949304.png">

**Comment by jstac** [comment]
Looks great, thanks @DrDrij .

**Comment by mmcky** [comment]
thanks @DrDrij the live sites are fed from the rst versions for now. 

`lecture-python-programming`, `lecture-python` and `lecture-python-advanced` along with their associated `.theme` repos.

**Comment by DrDrij** [comment]
https://github.com/QuantEcon/lecture-python-advanced/pull/142
https://github.com/QuantEcon/lecture-python/pull/245
https://github.com/QuantEcon/lecture-python-programming/pull/70
🤙

**Comment by DrDrij** [comment]
https://github.com/QuantEcon/lecture-python.theme/pull/16
https://github.com/QuantEcon/lecture-python-advanced.theme/pull/13
https://github.com/QuantEcon/lecture-python-programming.theme/pull/18
