### ISSUE TITLE
[AWS] Certificate SSL for www.quantecon.org

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#48]
@DrDrij would you mind to look at the config for `aws`

Reported by Jesse Perla

> Very minor, but just in case it masks something bigger:
I went to https://www.quantecon.org instead of just the https://quantecon.org   and it is yelling back that the https certificate isn't valid.  maybe because you are trying to forward it to quantecon.org.  I dont think this is especially important on its own, but there might be a number of existing site pointing to the old www. site.

**Comment by DrDrij** [comment]
Currently `www.` is pointing a CNAME record to `confident-meninsky-7329c2.netlify.com`.

There is an S3 (with redirect) and Cloudfront with SSL already setup.

I am changing the record to point to AWS and it appears that is has resolved the problem.
