### ISSUE TITLE
data files pointing to old lecture-source-py repo

### ISSUE THREAD

**Issue by Harveyt47** [QuantEcon/meta#5]
We need to update links and data files that point to the old `lecture-source-py` repo and point them  to their correct repo.

for example in [mle](https://python.quantecon.org/mle.html#Counting-Billionaires) the first data frame point should point to 
`https://github.com/QuantEcon/lecture-python/blob/master/source/_static/lecture_specific/mle/fp.dta?raw=true`

**Comment by mmcky** [comment]
can you please submit a PR?

**Comment by jstac** [comment]
Good catch @Harveyt47 .  This affects a few lectures across multiple repos (pandas.rst, ols.rst, mle.rst, pandas_panel.rst).

**Comment by Harveyt47** [comment]
Hi @jstac I have done a search across the repo's and have made a number of PR's fixing this.

**Comment by mmcky** [comment]
@Harveyt47 are all cases fixed? Please go ahead and close this if so -- otherwise document any remaining cases. Thanks.
