### ISSUE TITLE
Enabling Access to GPU for Lecture Builds

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#56]
The default `GitHub actions` hardware is `cpu` based so there are no `gpu's` available.

To support lecture compilation we may need to add our own `runners` that we can connect to `GitHub`

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

For the build / ci jobs to run on. These on-site servers could be based at `anu` or in the `cloud` -- but on-premise allows us to fully cater to specific hardware selections.

**Comment by mmcky** [comment]
Looks like the machine is connected directly -- but it would be nice to have a clean environment every time something is built (given that is how `GitHub actions` works and the workflows are built around that assumption)

https://testdriven.io/blog/github-actions-docker/

**Comment by mmcky** [comment]
The main issue from `GitHub docs` is that runners execute code from `forks` so it is advised to use them on `private` repositories only as a `fork` could send malicious code to the server.

**Comment by jstac** [comment]
Thanks for working on this @mmcky .  I'm writing another GPU-based lecture right now :-)

**Comment by mmcky** [comment]
Another option would be to use an external provider for those workflows that require a `GPU` such as `circleci`

https://circleci.com/execution-environments/

They offer a GPU context.

**Comment by mmcky** [comment]
I have opened a ticket to check with GitHub support

https://support.github.com/ticket/personal/0/1548122

**Comment by mmcky** [comment]
@jstac I have written to `gihtub` support and they have indicated they are working on adding support for higher spec machines (including some with `gpu` hardware) -- but there is no timeline. 

So perhaps the best `short term` solution is to use `private repos` for:

1. QuantEcon.manual
2.  Future series on GPU

**Comment by jstac** [comment]
Hey @mmcky , how would using private repos help with GPUs?

**Comment by mmcky** [comment]
@jstac with a private repo (in the `short term`) we can then easily connect a `custom` runner which is hosted on a machine in our office -- that `GitHub` can dispatch to for running the compilation work (on hardware with a `gpu`). When `GitHub` supports `gpu` instances we can then `open` the repo serving the `gpu` lectures and transfer the workloads back on the the `GitHub Actions` service.

**Comment by mmcky** [comment]
There are some security issues we need to consider when running a local GitHub runner (on a public repo). 

But GitHub Actions is working on support https://github.com/github/roadmap/issues/505 which is the preferred solution

**Comment by mmcky** [comment]
This is also useful project that might help us run locally

https://cml.dev/doc 

through docker containers.

**Comment by mmcky** [comment]
OK I think the best setup will be:

1. setup a CML self hosted runner on an aws `p2.xlarge` ($0.9/hour) which will launch and destroy docker container powered instances when tasks request them. That way `aws` is only running when we need compute

**Benefits:**

1. This will be `robust` as instance is hosted on `aws`
2. Provides access to `NVIDIA K80 GPU`

The only downside is that it costs money to run the `aws` instance but should be ~$0.9 for each run.

**Comment by mmcky** [comment]
This is now up and running on https://github.com/QuantEcon/lecture-python-programming.myst/pull/237

However we need to use `V100` cards instead of `K80` as the `K80` is deprecated and doesn't work well with `jax`. 

- [ ] setup a `quantecon` docker container that includes `latex` and `conda` to speed up preview builds based off of the Nvidia docker containers with `gpu` driver support

**Comment by jstac** [comment]
Nice work @mmcky .  It's been a struggle but I'm sure it will be worth it.

**Comment by mmcky** [comment]
Thanks @jstac it is fun now that we have it working `:-)`. 

There are a lot of variables and I hadn't focused on hardware thinking nvidia drivers didn't change that much. I am trying to find a good resource on hardware recommendations for GPU support with `jax`.

**Comment by mmcky** [comment]
Closing this and will track remaining task separately.
