### ISSUE TITLE
Add contributor page to each python lecture series?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#6]
@jstac @thomassargent30 perhaps we can add a contributor page to each `python` lecture series as `source/rst/contributors.rst` and then update the current "see all contributors" to this page. 

<img width="948" alt="image" src="https://user-images.githubusercontent.com/8263752/82277589-94147180-99cb-11ea-9da8-26cb3b3240d9.png">

A page that is manually updated is probably more meaningful than the current github commit history - as a lot of that history is `infrastructure` related rather than content related.

**Comment by sayaikegawa** [comment]
Hi @mmcky , I'm going to make each rst file about contributors related to each repo.
But seemingly I do not receive the list, if you have it, could you please put it here?
Or would it be ok to make the files just from [the current contributor page](https://quantecon.org/about-python-lectures/)

**Comment by mmcky** [comment]
thanks @sayaikegawa -- my only hesitation is to have information in both places. @jstac do you think we should have a central place for contributors or a separate `contributors` page for each lecture series -> that is linked to from the front page (as I had suggested as a possible change above)?

**Comment by mmcky** [comment]
> Or would it be ok to make the files just from the current contributor page

Yes - This would be the best information source for this work.

**Comment by jstac** [comment]
Well, this page is quite informative: https://quantecon.org/about-python-lectures/.

Is there a way to link to the heading "Credits"?  Then perhaps "View all contributors" on each of the three pages should simply point to that?

Those who want to look up GH commit histories can do it easily enough.  So we don't really need to point to it.

The "Credits" could be updated slightly by mentioning Saya, Harvey, Shu, Aakash and Juna as research assistants.

How does that sound @mmcky and @sayaikegawa ?

**Comment by mmcky** [comment]
@DrDrij is there a way to enable `id` tags for headings on the `orgsite` build?

**Comment by mmcky** [comment]
@jstac I think that is a nice idea. The orgsite is a `jekyll` build so we should be able to enable direct linking to title: `Credit`

**Comment by sayaikegawa** [comment]
@jstac , I think that is a nice idea too. And I'll update it. Is Miles also RA to add the page?

**Comment by DrDrij** [comment]
It should definitely be possible. An example would be changing the credits heading to:

`## Credits {#credits}`

You can then link directly so the page jumps directly to the heading with: https://quantecon.org/about-python-lectures/#credits

Source: https://www.markdownguide.org/extended-syntax/#heading-ids

**Comment by mmcky** [comment]
thanks @DrDrij that is helpful. I guess the rule of thumb is that section titles will always have an id but it is hard to know for mutli-word titles if the spaces are added or hyphened etc. 

Is there a way to make a link indicator show up. 

An example of what I mean is here:

https://www.sphinx-doc.org/en/master/intro.html#conversion-from-other-systems
